typography_spectrum: 0.6833022
content_rating:
  adult: false
color:
  saturation: 0.7383395
  lightness: 0.5027985
  brandStrength: 0.4986008
  brandColors:
    - '#2E070A'
    - '#FFFFFF'
    - '#737069'
    - '#B3B1A5'
    - '#A61E2C'
  rhythmicContrast: 0.7448694
github: true
layout_spectrum: 0.2527985
analytics:
  google: UA-91386704-1
author:
  name: Janina Adomski
  email: janina@abachamusic.com.au
  url: 'http://www.abachamusic.com.au/'
name: Abacha Music
url: 'http://abachamusic.com.au/'
navigation:
  - name: Music Lessons
    id: 0a0f5246-43bf-4cf3-a8ca-5c4cc15c36cc
    type: content
  - name: Music Theory Books
    id: e3d09aaa-e2a9-4ab4-ac69-bd3f7f4846bf
    type: content
  - name: Musical Instruments Textbook
    id: 93adf380-f5e5-473f-886f-c3a2af75bd1e
    type: content
  - name: Contact Details
    id: c86f05ed-135a-4531-9d57-4afb505479b4
    type: content
  - name: About Me
    id: 9f2b83d8-deac-4f50-8af3-f5bbe88eac6b
    type: content
title: Abacha Music
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd5c9383-101a-4083-8893-947f2ea396c9.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd5c9383-101a-4083-8893-947f2ea396c9.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9b149fae-1543-4e7a-82c7-2da4e57db7f5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9b149fae-1543-4e7a-82c7-2da4e57db7f5.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Janina Adomski
purpose:
  - type: internal
    label: Contact Me!
    item: c86f05ed-135a-4531-9d57-4afb505479b4
