name: Abacha Music
analytics:
  google: UA-91386704-1
purpose:
  - type: internal
    label: Contact Me!
    item: c86f05ed-135a-4531-9d57-4afb505479b4
github: true
description: Janina Adomski
author:
  name: Janina Adomski
  url: 'http://www.abachamusic.com.au/'
  email: janina@abachamusic.com.au
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd5c9383-101a-4083-8893-947f2ea396c9.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd5c9383-101a-4083-8893-947f2ea396c9.jpg
    metadata:
      author: []
      '@context': 'http://schema.org'
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      app_links: []
      related: []
      description: ''
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9b149fae-1543-4e7a-82c7-2da4e57db7f5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9b149fae-1543-4e7a-82c7-2da4e57db7f5.jpg
    metadata:
      author: []
      '@context': 'http://schema.org'
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      app_links: []
      related: []
      description: ''
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: 0a0f5246-43bf-4cf3-a8ca-5c4cc15c36cc
    name: Music Lessons
    type: content
  - id: e3d09aaa-e2a9-4ab4-ac69-bd3f7f4846bf
    name: Music Theory Books
    type: content
  - id: 93adf380-f5e5-473f-886f-c3a2af75bd1e
    name: Musical Instruments Textbook
    type: content
  - id: 9f2b83d8-deac-4f50-8af3-f5bbe88eac6b
    name: About Me
    type: content
  - id: c86f05ed-135a-4531-9d57-4afb505479b4
    name: Contact Details
    type: content
layout_spectrum: 0.2527985
color:
  lightness: 0.5027985
  brandColors:
    - '#2E070A'
    - '#FFFFFF'
    - '#737069'
    - '#B3B1A5'
    - '#A61E2C'
  saturation: 0.7383395
  brandStrength: 0.4986008
  rhythmicContrast: 0.7448694
content_rating:
  adult: false
typography_spectrum: 0.6833022
opengraph: {}
title: Abacha Music
url: 'http://abachamusic.com.au/'
